#ifndef STATE_H
#define	STATE_H

enum STATE_ID
{
    STATE_MESSAGE,
    STATE_TIME_CLOCK,
    STATE_TIME_SET,
    STATE_ALARM_SET,
    STATE_SEC_SET,
    STATE_SNOOZE_SET,
    STATE_SENSOR,
    //STATE_TUNE_SET,
    STATE_VOLUME_SET,
    //STATE_BRIGHT_SET,
    NUM_STATES
};

#define DEFAULT_STATE STATE_TIME_CLOCK

#endif	/* STATE_H */

